services:
  - type: web
    name: docmify-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000
